on:
  workflow_call:
    inputs:
      verdaccio-version:
        description: 'Verdaccio version to use'
        required: false
        default: 'latest'
        type: string

jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Publish
      uses: verdaccio/github-actions/publish@master # always latest by design 
      with:
        args: -d
        verdaccio-version: ${{ inputs.verdaccio-version }}
