on:
  workflow_call:
  
jobs:
  npm10:
    name: 'npm10:audit example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 'Use Node.js'
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: '.nvmrc'
      - name: 'install latest npm 10'
        run: npm i -g npm@next-10  
      - name: Install Dependencies
        run: yarn install
      - name: 'Run verdaccio in the background'
        run: |
          nohup yarn node ./scripts/run-verdaccio.js  --config ./scripts/e2e-config.yaml  &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --yes
          npm install next --registry http://localhost:4873  --loglevel info
          npm audit
